name: BuildingGame
version: 0.1
main: andrew.BuildingGame.Main

commands:
  bghost:
    description: Sets the host for the Building Game
    usage: /bghost
  bgready:
    description: Toggles player ready status for a Building Game
    usage: /bgready
  bgstart:
    description: Starts a Building Game with all ready players
    usage: /bgstart
  bgprompt:
    description: Add a prompt suggestion
    usage: /bgprompt <prompt>
  bgnext:
    description: Teleports all players to their location for the next phase
    usage: /bgnext
  bgsettings:
    description: Get or set game settings
    usage: /bgsettings <get,set> <newValue>